# Generated by Django 5.2.14 on 2026-05-30 22:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("paperless", "0010_alter_applicationconfiguration_llm_embedding_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="llm_backend",
            field=models.CharField(blank=True, choices=[("openai-like", "OpenAI-compatible"), ("ollama", "Ollama"), ("mistral", "Mistral AI")], max_length=128, null=True, verbose_name="Sets the LLM backend"),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="llm_embedding_backend",
            field=models.CharField(blank=True, choices=[("openai-like", "OpenAI-compatible"), ("huggingface", "Huggingface"), ("ollama", "Ollama"), ("mistral", "Mistral AI")], max_length=128, null=True, verbose_name="Sets the LLM embedding backend"),
        ),
    ]
