# Generated by Django 5.2.7 on 2025-10-11 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1068_alter_document_created"),
        ("documents", "1068_remove_document_ocr_image_paths_and_more"),
    ]

    operations = []
