# Generated by Django 5.2.10 on 2026-01-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1069_merge_20251011_1011'),
        ('documents', '1075_workflowaction_order'),
    ]

    operations = [
    ]
