import {
  Archive,
  ArrowDown,
  ArrowDownAZ,
  ArrowLeft,
  ArrowRight,
  ArrowUpAZ,
  ArrowUpDown,
  ArrowUpRight,
  Asterisk,
  AtSign,
  Bell,
  Bookmark,
  Braces,
  Calendar,
  CalendarDays,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleMinus,
  CirclePlus,
  CircleSlash,
  CircleUser,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Dice5,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  File,
  FileCheck,
  FileDiff,
  FileLock,
  FilePlus,
  FileText,
  Files,
  Filter,
  Folder,
  Funnel,
  GripVertical,
  Hash,
  Heading,
  History,
  House,
  IndentIncrease,
  Info,
  Layers,
  LayoutGrid,
  Library,
  Link,
  List,
  ListChecks,
  ListTodo,
  ListTree,
  LockOpen,
  LogOut,
  X as LucideX,
  Mail,
  MessageSquareText,
  Minus,
  Pencil,
  Plane,
  Play,
  Plus,
  Printer,
  RotateCcw,
  RotateCw,
  ScanBarcode,
  Scissors,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  SlidersVertical,
  Sparkles,
  Tags,
  Text,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  UserLock,
  Users,
  Workflow,
} from 'lucide-angular'

export const PAPERFLOW_ICONS = {
  ArrowRepeat: RotateCw,
  ChevronDown,
  ChevronUp,
  Tag: Tags,
  PersonSquare: CircleUser,
  EnvelopeAt: AtSign,
  ChatSquareDots: MessageSquareText,
  // chrome / navigation
  House,
  Files,
  FileText,
  Stack: Layers,
  Tags,
  TagFill: Tags,
  Person: User,
  PersonFill: User,
  Hash,
  Folder,
  FolderFill: Folder,
  UiRadios: ListChecks,
  WindowStack: Bookmark,
  Boxes: Workflow,
  Envelope: Mail,
  Trash: Trash2,
  Gear: Settings,
  Sliders2Vertical: SlidersVertical,
  People: Users,
  ListTask: ListTodo,
  TextLeft: ScrollText,
  QuestionCircle: CircleHelp,
  InfoCircle: Info,
  ChevronDoubleRight: ChevronsRight,
  ChevronDoubleLeft: ChevronsLeft,
  GripVertical,
  DoorOpen: LogOut,
  PersonCircle: CircleUser,
  Funnel,
  X: LucideX,
  // actions / status
  ExclamationTriangleFill: TriangleAlert,
  ExclamationTriangle: TriangleAlert,
  ExclamationCircleFill: CircleAlert,
  Check,
  CheckLg: Check,
  Check2All: CheckCheck,
  CheckAll: CheckCheck,
  CheckCircle: CircleCheck,
  CheckCircleFill: CircleCheck,
  PlusCircle: CirclePlus,
  Plus,
  NodePlus: CirclePlus,
  Pencil,
  Eye,
  ThreeDotsVertical: EllipsisVertical,
  ThreeDots: Ellipsis,
  Filter,
  SlashCircle: CircleSlash,
  ArrowCounterclockwise: RotateCcw,
  ArrowClockwise: RotateCw,
  Download,
  Upload,
  BoxArrowUp: Upload,
  BoxArrowUpRight: ExternalLink,
  Link,
  Send,
  Airplane: Plane,
  Search,
  PlayFill: Play,
  Scissors,
  Printer,
  Archive,
  Dash: Minus,
  DashCircle: CircleMinus,
  Asterisk,
  Stars: Sparkles,
  Braces,
  UpcScan: ScanBarcode,
  // files / clipboard
  FileEarmark: File,
  FileEarmarkFill: File,
  FileEarmarkRichtext: FileText,
  FileEarmarkCheck: FileCheck,
  FileEarmarkPlus: FilePlus,
  FileEarmarkLock: FileLock,
  FileEarmarkDiff: FileDiff,
  Clipboard,
  ClipboardFill: Clipboard,
  ClipboardCheck,
  ClipboardCheckFill: ClipboardCheck,
  CardChecklist: ClipboardList,
  CardHeading: Heading,
  BodyText: Text,
  Journals: Library,
  ListUl: List,
  ListNested: ListTree,
  // people / permissions
  PersonLock: UserLock,
  PersonFillLock: UserLock,
  PeopleFill: Users,
  Unlock: LockOpen,
  // calendar / dates / misc
  Calendar,
  CalendarEvent: CalendarDays,
  CalendarEventFill: Calendar,
  ClockHistory: History,
  Bell,
  ChatLeftText: MessageSquareText,
  EnvelopeAtFill: AtSign,
  Diagram3: Workflow,
  HddStack: Server,
  Grid: LayoutGrid,
  Dice5,
  Circle,
  // arrows / carets / chevrons / sorting
  ArrowRight,
  ArrowRightShort: ArrowRight,
  ArrowLeft,
  ArrowDown,
  ArrowUpRight,
  ArrowDownUp: ArrowUpDown,
  ChevronRight,
  CaretUp: ChevronUp,
  CaretDown: ChevronDown,
  SortAlphaDown: ArrowDownAZ,
  SortAlphaUpAlt: ArrowUpAZ,
  XCircle: CircleX,
  XLg: LucideX,
  TextIndentLeft: IndentIncrease,
}
