DavLockDB /tmp/DavLock

DocumentRoot /dav

<Directory /dav>
    DAV On
    AuthType Basic
    AuthName "Paperflow"
    AuthUserFile /usr/local/apache2/conf/webdav.passwd
    Require valid-user
    Options None
</Directory>
